version: '3.7'

services:
  nifi1:
    image: apache/nifi:latest
    networks:
      - public 
        #hostname: nifi1
    ports:
      - "8087:8080"
    user: root
    environment:
      - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,address=8000,server=y,suspend=n
    volumes:
      - /home/docker/nifi.cluster.docker.swarm/nifi1/nifi.properties:/opt/nifi/conf/nifi.properties:ro
      - /home/docker/nifi.cluster.docker.swarm/nifi1/bootstrap.conf:/opt/nifi/conf/bootstrap.conf:ro
      - /home/docker/srv/nifi/flow:/opt/nifi/flow:Z
      - /home/docker/srv/nifi/content_repository:/opt/nifi/content_repository:Z
      - /home/docker/srv/nifi/database_repository:/opt/nifi/database_repository:Z
      - /home/docker/srv/nifi/flowfile_repository:/opt/nifi/flowfile_repository:Z
      - /home/docker/srv/nifi/provenance_repository:/opt/nifi/provenance_repository:Z
      - /home/docker/srv/nifi/work:/opt/nifi/work:Z
      - /home/docker/srv/nifi/logs:/opt/nifi/logs:Z
      - /home/docker/tmp/data:/tmp/data:Z
#    healthcheck:
#      test: ["CMD", "wget","-q","http://localhost:8080","-O","/dev/null"]
#      interval: 30s
#      timeout: 10s
#      retries: 300
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.host == deep-learning-workstation]
  nifi2:
    image: apache/nifi:latest
    networks:
      - public 
        #hostname: nifi2
    ports:
      - "8085:8080"
    user: root
    environment:
      - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,address=7000,server=y,suspend=n
    volumes:
      - /home/docker/nifi.cluster.docker.swarm/nifi2/nifi.properties:/opt/nifi/conf/nifi.properties:ro
      - /home/docker/nifi.cluster.docker.swarm/nifi2/bootstrap.conf:/opt/nifi/conf/bootstrap.conf:ro
      - /home/docker/srv/nifi/flow:/opt/nifi/flow:Z
      - /home/docker/srv/nifi/content_repository:/opt/nifi/content_repository:Z
      - /home/docker/srv/nifi/database_repository:/opt/nifi/database_repository:Z
      - /home/docker/srv/nifi/flowfile_repository:/opt/nifi/flowfile_repository:Z
      - /home/docker/srv/nifi/provenance_repository:/opt/nifi/provenance_repository:Z
      - /home/docker/srv/nifi/work:/opt/nifi/work:Z
      - /home/docker/srv/nifi/logs:/opt/nifi/logs:Z
      - /home/docker/tmp/data:/tmp/data:Z
#    healthcheck:
#      test: ["CMD", "wget","-q","http://localhost:8085","-O","/dev/null"]
#      interval: 30s
#      timeout: 10s
#      retries: 300
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname == hp-z620-workstation]
  nginx1:
    image: "nginx"
    networks:
      - public 
    ports:
      - "80:80"
    volumes:
      - /home/docker/nifi.cluster.docker.swarm/nginx1/:/etc/nginx/conf.d/:ro
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname == deep-learning-workstation]
  nginx2:
    image: "nginx"
    networks:
      - public 
    ports:
      - "85:85"
    volumes:
      - /home/docker/nifi.cluster.docker.swarm/nginx2/:/etc/nginx/conf.d/:ro
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname == hp-z620-workstation]
                
networks:
  public:
    external: true
    name: public
